#!/usr/bin/env python3
"""
SLD fitting using calligraph library.
This is the baseline used in our paper.
Reads initial points from a file generated by extract.py.

Usage:
    1. First run extract.py with nsplat environment:
       conda activate nsplat
       python extract.py --input data/rose.png --output data/rose_points.npz

    2. Then run this script with calligraph environment:
       conda activate calligraph
       python berio.py
"""

import argparse
import pathlib
import time

import numpy as np
import torch
from PIL import Image

# Calligraph imports
from calligraph import (
    geom,
    config,
    diffvg_utils,
    spline_losses,
    image_losses,
)


def get_args():
    parser = argparse.ArgumentParser(
        description="Fit B-splines using calligraph (Berio)"
    )
    parser.add_argument("--input", type=str, default=None, help="Input image path")
    parser.add_argument(
        "--points", type=str, default=None, help="Points .npz file path"
    )
    parser.add_argument("--output-dir", type=str, default=None, help="Output directory")
    return parser.parse_args()


_cli_args = get_args()

device = config.device
dtype = torch.float32

##### BEGIN CONFIG #####
input_file = (
    pathlib.Path(_cli_args.input) if _cli_args.input else pathlib.Path("data/1.png")
)
points_file = (
    pathlib.Path(_cli_args.points) if _cli_args.points else pathlib.Path("data/1.npz")
)
output_dir = (
    pathlib.Path(_cli_args.output_dir)
    if _cli_args.output_dir
    else pathlib.Path("output_berio")
)

# Spline settings
degree = 5
deriv = 3
multiplicity = 1
b_spline = 1
pspline = 0
if deriv >= degree:
    pspline = 1
closed = False
seed = 133
alpha = 1.0

# Stroke width settings
stroke_width = 10.0
minw, maxw = 0.0, 50.0
vary_width = 1

# Optimization settings
lr_pos = 1.5
lr_width = 0.3
num_opt_steps = 150

# Loss weights
smoothing_w = 3.0
mse_w = 20.0
bbox_w = 10.0
mse_mul = 1.0

vis_every = 1
##### END CONFIG #####

torch.manual_seed(seed)
np.random.seed(seed)

# Load and preprocess input image
input_img = Image.open(input_file).convert("L")
img = np.array(input_img) / 255.0
h, w = img.shape

target_img = img  # Target is the input image
background_image = np.ones((h, w))

# Load points from file generated by extract.py
print(f"Loading points from {points_file}...")
data = np.load(points_file)
num_strokes = int(data["num_strokes"][0])
pts_list = [data[f"stroke_{i}"] for i in range(num_strokes)]
print(f"Loaded {len(pts_list)} stroke(s)")

# Use downsampled points directly as keypoints
startup_paths = []
for pts in pts_list:
    # Add stroke width as third column
    widths = np.full((pts.shape[0], 1), stroke_width, dtype=np.float32)
    Pw = np.concatenate([pts.astype(np.float32), widths], axis=1)
    print(f"Created initial path with {Pw.shape[0]} key points.")
    # Add multiplicity
    Pw = np.kron(Pw, np.ones((multiplicity, 1)))
    startup_paths.append(Pw)

##############################################
# Create the scene

scene = diffvg_utils.Scene()

paths = []
for Pw in startup_paths:
    if b_spline:
        path = diffvg_utils.SmoothingBSpline(
            Pw[:, :2],
            stroke_width=(Pw[:, 2], True),
            degree=degree,
            pspline=pspline,
            split_pieces=alpha < 1,
            closed=closed,
        )
    else:
        path = diffvg_utils.CardinalSpline(
            Pw[:, :2],
            stroke_width=(Pw[:, 2], True),
            closed=closed,
        )
    paths.append(path)

scene.add_shapes(
    paths,
    stroke_color=([alpha], False),
    fill_color=None,
    split_primitives=False,
)

##############################################
# Optimization

params = [(scene.get_points(), lr_pos)]
if vary_width:
    params += [(scene.get_stroke_widths(), lr_width)]

opt = diffvg_utils.SceneOptimizer(
    scene,
    params=params,
    num_steps=num_opt_steps,
    lr_min_scale=0.1,
)

##############################################
# Losses

opt.add_loss(
    "mse",
    image_losses.MultiscaleMSELoss(rgb=False),
    mse_w,
    inputs=("im", "input_img", "mse_mul"),
)

opt.add_loss(
    "bbox",
    spline_losses.make_bbox_loss(geom.rect(0, 0, w, h)),
    bbox_w,
    inputs=("points",),
)

if degree > 3 and b_spline:
    opt.add_loss(
        "deriv",
        spline_losses.make_deriv_loss(deriv, w),
        smoothing_w,
        inputs=("shapes",),
    )


##############################################
# Optimization

output_dir.mkdir(parents=True, exist_ok=True)


def save_gray(arr, path):
    """Save a [0,1] float grayscale array as a PNG image."""
    Image.fromarray((np.clip(arr, 0.0, 1.0) * 255).astype(np.uint8), mode="L").save(
        path
    )


# Save input image
save_gray(target_img, output_dir / "input.png")

print("Starting optimization...")
time_start = time.perf_counter()
final_image = None

for step in range(num_opt_steps):
    opt.zero_grad()
    im = opt.render(background_image)[:, :, 0].to(device)

    opt.step(
        im=im,
        points=scene.get_points(),
        input_img=target_img,
        shapes=scene.shapes,
        mse_mul=mse_mul,
    )

    # Constrain stroke widths
    with torch.no_grad():
        for path in paths:
            path.param("stroke_width").data.clamp_(minw, maxw)

    elapsed = time.perf_counter() - time_start

    if step % vis_every == 0 or step == num_opt_steps - 1:
        im_np = im.detach().cpu().numpy()
        print(f"step {step:04d} | elapsed: {elapsed:.2f}s")
        save_gray(im_np, output_dir / f"step_{step:04d}.png")

    final_image = im

final_time = time.perf_counter() - time_start
print(
    f"\nOptimization finished in {final_time:.2f}s (average {final_time/num_opt_steps:.2f}s per step)"
)
final_path = output_dir / "final.png"
save_gray(final_image.detach().cpu().numpy(), final_path)
print(f"Saved final rendering to '{final_path}'")
