"""
SLD fitting using nurbs splatting.
Reads initial points from a file generated by extract.py.

Usage:
    1. First run extract.py with nsplat environment:
       conda activate nsplat
       python extract.py --input data/rose.png --output data/rose_points.npz

    2. Then run this script with nsplat environment:
       conda activate nsplat
       python fit.py
"""

import argparse
import math
import pathlib
import time
from typing import Literal

import numpy as np
import torch
from PIL import Image

from nsplat import image_losses
from nsplat.nurbs import NURBSSplat
from nsplat.scene import NURBSScene
from nsplat.spline_losses import make_bbox_loss, make_deriv_loss
from nsplat.utils import make_cosine_lr_scheduler


def get_args():
    parser = argparse.ArgumentParser(description="Fit NURBS splines to an image")
    parser.add_argument("--input", type=str, default=None, help="Input image path")
    parser.add_argument(
        "--points", type=str, default=None, help="Points .npz file path"
    )
    parser.add_argument("--output-dir", type=str, default=None, help="Output directory")
    parser.add_argument(
        "--lr-pos", type=float, default=1.5, help="Learning rate for key_points"
    )
    parser.add_argument(
        "--lr-width",
        type=float,
        default=0.2,
        help="Learning rate for stroke_width",
    )
    parser.add_argument(
        "--lr-weight", type=float, default=0.1, help="Learning rate for weights"
    )
    parser.add_argument(
        "--lr-knot",
        type=float,
        default=0.1,
        help="Learning rate for knot_interval",
    )
    parser.add_argument(
        "--density",
        type=float,
        default=18,  # set as 30 for a denser fit
        help="Gaussian sampling density along strokes",
    )
    parser.add_argument(
        "--scale-ratio",
        type=float,
        default=2.0,
        help="Gaussian scale_ratio (higher = narrower Gaussians)",
    )
    return parser.parse_args()


_cli_args = get_args()

##### BEGIN CONFIG #####
# Note: First run extract.py with nsplat environment to generate the points file:
#   conda activate nsplat
#   python extract.py --input data/line_arts/v_clave.jpg --output data/v_clave_points.npz

input_file = (
    pathlib.Path(_cli_args.input) if _cli_args.input else pathlib.Path("data/1.png")
)
points_file = (
    pathlib.Path(_cli_args.points) if _cli_args.points else pathlib.Path("data/1.npz")
)
degree = 5

order = degree + 1  # NURBS order = degree + 1
density = _cli_args.density
seed = 133

stroke_width = 10.0
minw, maxw = 0.0, 50.0

# Learning rates — configurable via CLI
lr_pos = _cli_args.lr_pos
lr_width = _cli_args.lr_width
lr_weight = _cli_args.lr_weight
lr_knot = _cli_args.lr_knot

_lr_by_param = {
    "key_points": lr_pos,
    "stroke_width": lr_width,
    "weights": lr_weight,
    "knot_interval": lr_knot,
}
optimize_params = tuple(param for param, lr in _lr_by_param.items() if lr > 0)
if len(optimize_params) == 0:
    raise ValueError("At least one learning rate must be > 0.")

lr_schedule = True
lr_min_scale = 0.1

num_opt_steps = 150
vis_every = 1

# Gaussian splatting parameters
scale_ratio = _cli_args.scale_ratio

## MSE loss — dominant
mse_w = 1.0
mse_mul = 1.0
mse_decay = False
mse_w_end = 0.05

## Smoothing — gradual warmup, somewhat stronger for better regularization
smooth_order = 3
smooth_w = 1.0
smooth_w_growth = False
smooth_w_end = 10.0
deriv_approx_method = "analytical"

## Bounding-box loss
bbox_pad = 0.0
bbox_w = 5.0

closed = False

output_dir = (
    pathlib.Path(_cli_args.output_dir)
    if _cli_args.output_dir
    else pathlib.Path("output_ours")
)
##### END CONFIG #####

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(seed)
np.random.seed(seed)

output_dir.mkdir(parents=True, exist_ok=True)

# Load and preprocess input image
input_img = Image.open(input_file).convert("L")
img = np.array(input_img) / 255.0
h, w = img.shape

# Create target image (inverted for fitting black strokes on white background)
target_img = img  # Assuming input is already the target
background_image = np.ones((h, w))

# Load points from file generated by extract.py
print(f"Loading points from {points_file}...")
data = np.load(points_file)
num_strokes = int(data["num_strokes"][0])
pts_list = [data[f"stroke_{i}"] for i in range(num_strokes)]
print(f"Loaded {len(pts_list)} stroke(s)")

#### NURBS Splatting begins here

# Create NURBSScene to manage all splines
scene = NURBSScene(width=w, height=h)
scene.to(device)

# Create NURBS splat objects for all splines in pts_list
for pts in pts_list:
    ctrl_pts = np.array(pts)
    if ctrl_pts.shape[0] < order:
        # Upsample control points to match order
        indices = np.linspace(0, ctrl_pts.shape[0] - 1, order)
        ctrl_pts = np.interp(indices, np.arange(ctrl_pts.shape[0]), ctrl_pts)

    # Add stroke width as third dimension
    widths = np.full((ctrl_pts.shape[0], 1), stroke_width, dtype=np.float32)
    # Force first and last endpoint stroke widths to zero
    # widths[0] = 0.0
    # widths[-1] = 0.0
    key_points = np.concatenate([ctrl_pts.astype(np.float32), widths], axis=1)
    key_points_t = torch.tensor(key_points, device=device)
    weights_t = torch.ones(ctrl_pts.shape[0], device=device)

    if key_points.shape[0] < 2:
        continue
    print(f"Creating NURBS spline with {key_points.shape[0]} control points.")

    nurbs = NURBSSplat(
        key_points_t,
        weights_t,
        order,
        width=w,
        height=h,
        density=density,
        color=torch.tensor([0.0, 0.0, 0.0], device=device),
        closed=closed,
        scale_ratio=scale_ratio,
        minimum_sgm_x=0.3,  # Ensure minimum Gaussian size along curve
    )
    scene.add_nurbs(nurbs)

print(f"Created {len(scene)} NURBS splines for optimization.")

param_groups = scene.get_params(
    optimize=optimize_params,
    lrs={
        "key_points": lr_pos,
        "stroke_width": lr_width,
        "weights": lr_weight,
        "knot_interval": lr_knot,
    },
)
optimizer = torch.optim.Adam(param_groups, betas=(0.9, 0.999))

# Cosine LR scheduler — matches calligraph's step_cosine_lr_scheduler
if lr_schedule:
    scheduler = make_cosine_lr_scheduler(optimizer, num_opt_steps, lr_min_scale)
else:
    scheduler = None

target_t = torch.tensor(target_img, device=device, dtype=torch.float32)
mse_loss_fn = image_losses.MultiscaleMSELoss(rgb=False)

if smooth_w > 0.0 or smooth_w_growth:
    smooth_loss_fn = make_deriv_loss(
        smooth_order,
        ref_size=max(w, h),
        approx_method=deriv_approx_method,
    )
else:
    smooth_loss_fn = None
bbox_loss_fn = make_bbox_loss(((0.0, 0.0), (float(w), float(h))), pad=bbox_pad)

# Determine the derivative order needed for scene.splat()
_splat_deriv_order = (
    smooth_order
    if deriv_approx_method == "analytical" and (smooth_w > 0.0 or smooth_w_growth)
    else 0
)


def save_gray(arr, path):
    """Save a [0,1] float grayscale array as a PNG image."""
    Image.fromarray((np.clip(arr, 0.0, 1.0) * 255).astype(np.uint8), mode="L").save(
        path
    )


# Save input / target image
save_gray(target_img, output_dir / "input.png")

startup, _ = scene.splat(max_deriv_order=_splat_deriv_order)
im = startup
startup = startup.detach().cpu().numpy()[..., 0]
save_gray(startup, output_dir / "startup.png")

print("Starting optimization...")
time_start = time.perf_counter()
for step in range(num_opt_steps):
    optimizer.zero_grad()
    out, pts = scene.splat(max_deriv_order=_splat_deriv_order)
    im = out[..., 0]
    mse_loss = mse_loss_fn(im, target_t, mult=mse_mul)

    if mse_decay:
        curr_mse_w = mse_w * (mse_w_end / mse_w) ** (step / num_opt_steps)
    else:
        curr_mse_w = mse_w

    loss = curr_mse_w * mse_loss

    if smooth_loss_fn is not None:
        smooth_loss = smooth_loss_fn(scene.nurbs_list)
    else:
        smooth_loss = torch.tensor(0.0)

    if smooth_w_growth:
        curr_smooth_w = smooth_w + (smooth_w_end - smooth_w) * (step / num_opt_steps)
    else:
        curr_smooth_w = smooth_w

    loss = loss + curr_smooth_w * smooth_loss

    bbox_loss = bbox_loss_fn(scene.nurbs_list)
    loss = loss + bbox_w * bbox_loss

    loss.backward()
    optimizer.step()
    if scheduler is not None:
        scheduler.step()

    with torch.no_grad():
        for nurbs in scene.nurbs_list:
            nurbs._stroke_width.clamp_(minw, maxw)
            nurbs._key_points[:, 0].clamp_(0, nurbs.W)
            nurbs._key_points[:, 1].clamp_(0, nurbs.H)
            nurbs._weights.clamp_(0.01, 10.0)
            nurbs._knot_interval.clamp_(0.0, 2.0)

    if step % vis_every == 0 or step == num_opt_steps - 1:
        log_msg = (
            f"step {step:04d} | loss {loss.item():.6f} | mse {mse_loss.item():.6f}"
            f" | smooth {smooth_loss.item():.6f}"
        )
        if bbox_w > 0:
            log_msg += f" | bbox {bbox_loss.item():.6f}"
        elapsed = time.perf_counter() - time_start
        log_msg += f" | elapsed {elapsed:.2f}s"
        print(log_msg)
        render_np = im.detach().cpu().numpy()
        save_gray(render_np, output_dir / f"step_{step:04d}.png")

final_time = time.perf_counter() - time_start
print(
    f"\nOptimization finished in {final_time:.2f}s (average {final_time/num_opt_steps:.2f}s per step)"
)
final_path = output_dir / "final.png"
save_gray(im.detach().cpu().numpy(), final_path)
print(f"Saved final rendering to '{final_path}'")

json_path = output_dir / "final.json"
scene.export_to_json(str(json_path))
print(f"Saved scene JSON to '{json_path}'")

# Print statistics for all NURBS in the scene
all_weights = torch.cat([nurbs._weights for nurbs in scene.nurbs_list])
all_knot_intervals = torch.cat([nurbs._knot_interval for nurbs in scene.nurbs_list])

print(f"Total NURBS splines: {len(scene)}")
print("Weights max/min/mean (across all splines):")
weights_max = torch.max(all_weights).item()
weights_min = torch.min(all_weights).item()
weights_mean = torch.mean(all_weights).item()
print(f"  {weights_max:.4f} / {weights_min:.4f} / {weights_mean:.4f}")

print("Knot interval max/min/mean (across all splines):")
knot_interval_max = torch.max(all_knot_intervals).item()
knot_interval_min = torch.min(all_knot_intervals).item()
knot_interval_mean = torch.mean(all_knot_intervals).item()
print(f"  {knot_interval_max:.4f} / {knot_interval_min:.4f} / {knot_interval_mean:.4f}")

# nurbs = scene.nurbs_list[0]
# con0 = nurbs._key_points
# print(nurbs._weights)
# con0 = torch.cat([con0, nurbs._stroke_width.unsqueeze(1)], dim=1)
# print(con0)
